@startuml
cloud {
  [GitHub] as github
  [IDP] as idp
}

[Dev Machine] as dev

package "Public Cloud" {
  database "Database" as database
  database "KeyValue-DB" as keyvaluedb
  database "Queue" as queue
  
  [Container Registry] as registry

  node "Microservice" as micro {
    [API] as api
    [Web-UI] as web
    [Redirector] as redirector
  }
}

dev --> github
github -d-> registry : Deploy
micro --> registry : Pull Images
web --> api
web -r-> idp
api --> database
api --> queue : Publish
queue <-- redirector : Consume
redirector -d-> keyvaluedb
@enduml